# Site Settings
title: "Mononito Goswami"
description: "Applied Scientist at Amazon · PhD in Robotics, Carnegie Mellon University"
url: "https://mononito.com"
baseurl: ""
repository: "mononitogoswami/mononitogoswami.github.io"

# Author
author:
  name: "Mononito Goswami"
  email: "mononitogoswami98@gmail.com"
  avatar: "/images/mononitogoswami.jpeg"
  bio: "Applied Scientist at Amazon"
  location: "Seattle, WA"
  google_scholar: "https://scholar.google.co.in/citations?user=TgQ72t0AAAAJ&hl=en&oi=ao"
  semantic_scholar: "https://www.semanticscholar.org/author/Mononito-Goswami/147478215"
  github: "https://github.com/mononitogoswami"
  linkedin: "https://www.linkedin.com/in/mononitogoswami"
  orcid: "https://orcid.org/0000-0002-4117-5558"

# Analytics
google_analytics: "G-LBN2NKQTBC"

# Open Graph
og_image: "/images/site-logo.png"

# Build
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty

# Include/Exclude
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - _review

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      image: "/images/site-logo.png"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  sass_dir: _sass
  style: compressed
